### ISSUE TITLE
‘for’ loop initial declarations are only allowed in C99 mode

### ISSUE THREAD

**Issue by bbuchalter** [jhawthorn/fzy#3]
Pulled down master, ran `make`, got this:
```
osboxes@osboxes:~/bin/fzy(master)% make                                                                                                                                                                                                                                          {1}
cc -DVERSION=\"0.2\" -Wall -Wextra -g -O3 -pedantic -c -o fzy.o fzy.c
fzy.c: In function ‘clear’:
fzy.c:43:2: warning: ISO C90 forbids mixed declarations and code [-Wpedantic]
  size_t line = 0;
  ^
fzy.c: In function ‘draw_match’:
fzy.c:53:2: warning: ISO C90 forbids variable length array ‘positions’ [-Wvla]
  size_t positions[n + 1];
  ^
fzy.c:54:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (int i = 0; i < n + 1; i++)
  ^
fzy.c:54:2: note: use option -std=c99 or -std=gnu99 to compile your code
fzy.c:57:2: warning: ISO C90 forbids mixed declarations and code [-Wpedantic]
  double score = match_positions(search, choice, &positions[0]);
  ^
fzy.c:67:14: error: conflicting types for ‘i’
  for (size_t i = 0, p = 0; choice[i] != '\0'; i++) {
              ^
fzy.c:54:11: note: previous definition of ‘i’ was here
  for (int i = 0; i < n + 1; i++)
           ^
fzy.c:67:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (size_t i = 0, p = 0; choice[i] != '\0'; i++) {
  ^
fzy.c: In function ‘draw’:
fzy.c:96:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (size_t i = start; i < start + num_lines; i++) {
  ^
fzy.c:99:3: warning: ISO C90 forbids mixed declarations and code [-Wpedantic]
   const char *choice = choices_get(choices, i);
   ^
fzy.c: In function ‘run’:
fzy.c:128:2: warning: ISO C90 forbids mixed declarations and code [-Wpedantic]
  char ch;
  ^
fzy.c: In function ‘main’:
fzy.c:265:2: warning: ISO C90 forbids mixed declarations and code [-Wpedantic]
  choices_t choices;
  ^
fzy.c:277:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < benchmark; i++)
   ^
fzy.c:281:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (size_t i = 0; i < choices_available(&choices); i++) {
   ^
make: *** [fzy.o] Error 1
```

Not sure what other information would be helpful, please let me know how I can help debug.

**Comment by bbuchalter** [comment]
A `git bisect` indicates the `make` command started failing on https://github.com/jhawthorn/fzy/commit/de53af7e70bdc352513cabd40dcb4872052b701b

**Comment by jhawthorn** [comment]
Thanks Brian. I reverted that commit in 9cafcad66d9ecab194590df344090551be55575c

My gcc was in c99 mode by default :(
